package me.fadlan.passwordgen.password

class CharSet {
    companion object {
        val UPPERCASE = listOf(
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z'
        )
        val LOWERCASE = listOf(
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z'
        )
        val NUMBER = listOf('1', '2', '3', '4', '5', '6', '7', '8', '9', '0')
        val SPECIAL = listOf(
            '~',
            '!',
            '@',
            '#',
            '$',
            '%',
            '^',
            '&',
            '*',
            '?',
            ':',
            ';',
            '(',
            '/',
            ')',
            '>',
            '<',
            '+',
            '=',
            '-',
            '.'
        )
    }
}